// When DOM is fully loaded
jQuery(document).ready(function ($) {

	/* FlexSlider
	--------------------------------------------------*/
	
	$('.flexslider').flexslider({
	    namespace           : "flex-",           //{NEW} String: Prefix string attached to the class of every element generated by the plugin
	    selector            : ".slides > li",    //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
	    animation           : "fade",            //String: Select your animation type, "fade" or "slide"
	    easing              : "swing",           //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
	    direction           : "horizontal",      //String: Select the sliding direction, "horizontal" or "vertical"
	    reverse             : false,             //{NEW} Boolean: Reverse the animation direction
	    animationLoop       : true,              //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
	    smoothHeight        : false,             //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
	    startAt             : 0,                 //Integer: The slide that the slider should start on. Array notation (0 = first slide)
	    slideshow           : true,              //Boolean: Animate slider automatically
	    slideshowSpeed      : 7000,              //Integer: Set the speed of the slideshow cycling, in milliseconds
	    animationSpeed      : 600,               //Integer: Set the speed of animations, in milliseconds
	    initDelay           : 0,                 //{NEW} Integer: Set an initialization delay, in milliseconds
	    randomize           : false,             //Boolean: Randomize slide order
	     
	    // Usability features
	    pauseOnAction       : true,              //Boolean: Pause the slideshow when interacting with control elements, highly recommended.
	    pauseOnHover        : false,             //Boolean: Pause the slideshow when hovering over slider, then resume when no longer hovering
	    useCSS              : true,              //{NEW} Boolean: Slider will use CSS3 transitions if available
	    touch               : true,              //{NEW} Boolean: Allow touch swipe navigation of the slider on touch-enabled devices
	    video               : false,             //{NEW} Boolean: If using video in the slider, will prevent CSS3 3D Transforms to avoid graphical glitches
	     
	    // Primary Controls
	    controlNav          : true,              //Boolean: Create navigation for paging control of each clide? Note: Leave true for manualControls usage
	    directionNav        : true,              //Boolean: Create navigation for previous/next navigation? (true/false)
	    prevText            : "Previous",        //String: Set the text for the "previous" directionNav item
	    nextText            : "Next",            //String: Set the text for the "next" directionNav item
	     
	    // Secondary Navigation
	    keyboard            : true,              //Boolean: Allow slider navigating via keyboard left/right keys
	    multipleKeyboard    : false,             //{NEW} Boolean: Allow keyboard navigation to affect multiple sliders. Default behavior cuts out keyboard navigation with more than one slider present.
	    mousewheel          : false,             //{UPDATED} Boolean: Requires jquery.mousewheel.js (https://github.com/brandonaaron/jquery-mousewheel) - Allows slider navigating via mousewheel
	    pausePlay           : false,             //Boolean: Create pause/play dynamic element
	    pauseText           : 'Pause',           //String: Set the text for the "pause" pausePlay item
	    playText            : 'Play',            //String: Set the text for the "play" pausePlay item
	     
	    // Special properties
	    controlsContainer   : "",                //{UPDATED} Selector: USE CLASS SELECTOR. Declare which container the navigation elements should be appended too. Default container is the FlexSlider element. Example use would be ".flexslider-container". Property is ignored if given element is not found.
	    manualControls      : "",                //Selector: Declare custom control navigation. Examples would be ".flex-control-nav li" or "#tabs-nav li img", etc. The number of elements in your controlNav should match the number of slides/tabs.
	    sync                : "",                //{NEW} Selector: Mirror the actions performed on this slider with another slider. Use with care.
	    asNavFor            : "",                //{NEW} Selector: Internal property exposed for turning the slider into a thumbnail navigation for another slider
	});
	
	/* Quotes Rotator
	--------------------------------------------------*/
	
	$('ul.quotes').quote_rotator({
	    rotation_speed: 7000,
	    pause_on_hover: true,
	    randomize_first_quote: true
	});
	
	/* FancyBox (Lightbox)
	--------------------------------------------------*/
	
	$(".fancybox").fancybox({
	    helpers: {
	        overlay: {
	            locked: false
	        }
	    }
	});
	
	/* Sticky Navigation
	--------------------------------------------------*/
	
	$('.header-top').clingify({
	    breakpoint: 767,  // in pixels
	    extraClass: '',
	    throttle: 100,  // in milliseconds
	    
	    // Callback functions:
	    detached: $.noop,
	    locked: $.noop,
	    resized: $.noop
	});
		
	$(function() {
	    var header = $(".header-top");
	    $(window).scroll(function() {    
	        var scroll = $(window).scrollTop();
	    
	        if (scroll >= 50) {
	            header.removeClass('header-top').addClass("header-top-dark");
	        } else {
	            header.removeClass("header-top-dark").addClass('header-top');
	        }
	    });
	});
	
	/* Select Navigation (Mobile Menu)
	--------------------------------------------------*/

	selectnav('sf', {
	    label: 'NAVIGATION',
	    autoselect: false,
	    nested: true,
	    indent: '-'
	});

	/* Superfish (Dropdown Menu)
	--------------------------------------------------*/    

	$('ul.sf-menu').superfish({
	    delay: 100, // the delay in milliseconds that the mouse can remain outside a submenu without it closing
	    animation: {
	        opacity: 'show'
	    }, // an object equivalent to first parameter of jQuery’s .animate() method. Used to animate the submenu open
	    animationOut: {
	        opacity: 'hide'
	    }, // an object equivalent to first parameter of jQuery’s .animate() method Used to animate the submenu closed
	    speed: 'fast', // speed of the opening animation. Equivalent to second parameter of jQuery’s .animate() method
	    speedOut: 'fast', // speed of the closing animation. Equivalent to second parameter of jQuery’s .animate() method
	    cssArrows: true,
	    autoArrows: false,
	    disableHI: false,
	});
	
	/* FitVids Responsive Video
	--------------------------------------------------*/
	
	$(".container").fitVids();
	
	/* Overlay Vertical Alignment
	--------------------------------------------------*/

	$.fn.extend({
	    verticalAlign: function () {
	        //Iterate over the current set of matched elements
	        return this.each(function () {
	            var obj = $(this);
	            // calculate the new padding and height
	            var childHeight = obj.height();
	            var parentHeight = obj.parent().height();
	            var diff = Math.round(((parentHeight - childHeight) / 2));
	            // apply new values
	            obj.css({
	                "display": "block",
	                "margin-top": diff
	            });
	        });
	    }
	});
	var callback = function () {
	    $(".project-item .overlay .details").verticalAlign();
	    $(".team-thumbnail .overlay .details").verticalAlign();
	    $(".news-thumbnail .overlay .details").verticalAlign();
	};
	$(document).ready(callback);
	$(window).resize(callback);
	$(window).load(callback);
	
	/* Back to top Scroll
	--------------------------------------------------*/
	
	$("#back-to-top").hide();
	$(function () {
	    $(window).scroll(function () {
	        if ($(this).scrollTop() > 100) {
	            $('#back-to-top').fadeIn();
	        } else {
	            $('#back-to-top').fadeOut();
	        }
	    });
	    $('#back-to-top a').click(function () {
	        $('body,html').animate({
	            scrollTop: 0
	        }, 800);
	        return false;
	    });
	});
		
	/* Latest Tweet/Twitter Widget
	--------------------------------------------------*/
	
	  /*
	  * ### HOW TO CREATE A VALID ID TO USE: ###
	  * Go to www.twitter.com and sign in as normal, go to your settings page.
	  * Go to "Widgets" on the left hand side.
	  * Create a new widget for what you need eg "user timeline". 
	  * Feel free to check "exclude replies" if you dont want replies in results.
	  * Now go back to settings page, and then go back to widgets page, you should
	  * see the widget you just created. Click edit.
	  * Now look at the URL in your web browser, you will see a long number like this:
	  * 345735908357048478
	  * Use this as your ID below instead!
	  */
	
	  /**
	   * How to use fetch function:
	   * @param {string} Your Twitter widget ID.
	   * @param {string} The ID of the DOM element you want to write results to. 
	   * @param {int} Optional - the maximum number of tweets you want returned. Must
	   *     be a number between 1 and 20.
	   * @param {boolean} Optional - set true if you want urls and hash
	         tags to be hyperlinked!
	   * @param {boolean} Optional - Set false if you dont want user photo /
	   *     name for tweet to show.
	   * @param {boolean} Optional - Set false if you dont want time of tweet
	   *     to show.
	   * @param {function/string} Optional - A function you can specify to format
	   *     tweet date/time however you like. This function takes a JavaScript date
	   *     as a parameter and returns a String representation of that date.
	   *     Alternatively you may specify the string 'default' to leave it with
	   *     Twitter's default renderings.
	   * @param {boolean} Optional - Show retweets or not. Set false to not show.
	   * @param {function/string} Optional - A function to call when data is ready. It
	   *     also passes the data to this function should you wish to manipulate it
	   *     yourself before outputting. If you specify this parameter you  must
	   *     output data yourself!
	   */
	
	  // ##### Simple example 1 #####
	  // A simple example to get my latest tweet and write to a HTML element with
	  // id "tweets". Also automatically hyperlinks URLS and user mentions and
	  // hashtags.
	  //twitterFetcher.fetch('352711627528880128', 'latest-tweet', 1, true, false);
	  
	//if ($('body#home').length) {
	 //   twitterFetcher.fetch('371742073709273088', 'latest-tweet', 1, true, false);
	//};
	
	twitterFetcher.fetch('398872287425753088', 'twitter-feed', 2, true, false, true, dateFormatter);
	
	var month= new Array("January","February","March","April","May","June","July","August","September","October","November","December");
	
	function dateFormatter(date) {
		return  month[date.getMonth()] + ' ' + date.getDate() + ', ' + date.getFullYear();
	}	
	
	/* Google Map
	--------------------------------------------------*/
	
	if ($('body#contact').length) {
	    var map;
	    map = new GMaps({
	        div: '#map',
	        lat: 44.984926,
	        lng: -93.182541,
	        panControl: false, // Remove this line if you would like to show the pan control.
	        zoomControl: false, // Remove this line if you would like to show the zoom control.
	        scaleControl: false, // Remove this line if you would like to show the scale control.
	        streetViewControl: false, // Remove this line if you would like to show the street view control.
	        scrollwheel: false, // Remove this line if you would like to enable zooming of the map via mousewheel/touchpad.
	        draggable: false, // Remove this line if you would like to enable dragging of the map via mouse/touchpad.
	    });
	    map.drawOverlay({
	        lat: map.getCenter().lat(),
	        lng: map.getCenter().lng(),
	        content: '<div class="map-overlay"><i class="icon-compass icon-2x"></i><br />You can find us here<div class="map-overlay_arrow above"></div></div>',
	        verticalAlign: 'top',
	        horizontalAlign: 'center'
	    });
	};
	
	/* Pie Chart (http://rendro.github.io/easy-pie-chart/)
	--------------------------------------------------*/
	
	$('.percentage').easyPieChart({
	    animate: 1000,
	    size: 200,
	    barColor: '#6699A6',
	    trackColor: '#ddd',
	    scaleColor: false,
	    lineCap: 'butt',
	    lineWidth: 40
	});
	
	/* Accordion Widget
	--------------------------------------------------*/
	
	//Add Inactive Class To All Accordion Headers
	$('.accordion-header').toggleClass('inactive-header');
	//Set The Accordion Content Width
	var contentwidth = $('.accordion-header').width();
	//Open The First Accordion Section When Page Loads
	$('.accordion-header').first().toggleClass('active-header').toggleClass('inactive-header');
	$('.accordion-content').first().slideDown().toggleClass('open-content');
	// The Accordion Effect
	$('.accordion-header').click(function () {
	    if ($(this).is('.inactive-header')) {
	        $('.active-header').toggleClass('active-header').toggleClass('inactive-header').next().slideToggle().toggleClass('open-content');
	        $(this).toggleClass('active-header').toggleClass('inactive-header');
	        $(this).next().slideToggle().toggleClass('open-content');
	    } else {
	        $(this).toggleClass('active-header').toggleClass('inactive-header');
	        $(this).next().slideToggle().toggleClass('open-content');
	    }
	});
			
	/* Tabbed Content
	--------------------------------------------------*/
	
	$(".tab_content").hide();
	$(".tab_content:first").show();
	$("ul.tabs li").click(function () {
	    $("ul.tabs li").removeClass("active");
	    $(this).addClass("active");
	    $(".tab_content").hide();
	    var activeTab = $(this).attr("data-id");
	    $("#" + activeTab).fadeIn();
	});
	
	/* Toggles
	--------------------------------------------------*/
	
	$(function () { // run after page loads
	    $(".toggle_container").hide();
	    //Switch the "Open" and "Close" state per click then slide up/down (depending on open/close state)
	    $("p.trigger").click(function () {
	        $(this).toggleClass("active").next().slideToggle("normal");
	        return false; //Prevent the browser jump to the link anchor
	    });
	});
	// valid XHTML method of target_blank
	$(function () { // run after page loads
	    $('a[rel*=external]').click(function () {
	        window.open(this.href);
	        return false;
	    });
	});
		
	/* Contact Form
	--------------------------------------------------*/

	// Validate the contact form
	$('#contact-form').validate({
	    // Add requirements to each of the fields
	    rules: {
	        name: {
	            required: true,
	            minlength: 2
	        },
	        email: {
	            required: true,
	            email: true
	        },
	        message: {
	            required: true,
	            minlength: 10
	        }
	    },
	    // Specify what error messages to display
	    // when the user does something horrid
	    messages: {
	        name: {
	            required: "Please enter your name.",
	            minlength: jQuery.format("At least {0} characters required.")
	        },
	        email: {
	            required: "Please enter your email.",
	            email: "Please enter a valid email."
	        },
	        message: {
	            required: "Please enter a message.",
	            minlength: jQuery.format("At least {0} characters required.")
	        }
	    },
	    // Use Ajax to send everything to php/form.php
	    submitHandler: function (form) {
	        $("#submit").attr("value", "Sending...");
	        $(form).ajaxSubmit({
	            target: "#response",
	            success: function (responseText, statusText, xhr, $form) {
	                $(form).slideUp("fast");
	                $("#response").html(responseText).hide().slideDown("fast");
	            }
	        });
	        return false;
	    }
	});
     
	/* Form Placeholder Functionality for IE8/IE9
	--------------------------------------------------*/
	
	if (!Modernizr.input.placeholder) {
	    $(document).on('focus', '[placeholder]', function () {
	        var input = $(this);
	        if (input.val() == input.attr('placeholder')) {
	            input.val('');
	            input.removeClass('placeholder');
	        }
	    })
	    $(document).on('blur', '[placeholder]', function () {
	        var input = $(this);
	        if (input.val() == '' || input.val() == input.attr('placeholder')) {
	            input.addClass('placeholder');
	            input.val(input.attr('placeholder'));
	        }
	    })
	    $('[placeholder]').blur();
	    $(document).on('submit', 'form', function () {
	        $(this).find('[placeholder]').each(function () {
	            var input = $(this);
	            if (input.hasClass('placeholder') && input.val() == input.attr('placeholder')) {
	                input.val('');
	            }
	        })
	    });
	}
	
	/* Column clearing
	--------------------------------------------------*/
	
	
	/* Email Subscription 
	--------------------------------------------------*/
	email_regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i;
	$('#emailInput').keyup(function(event){
		email_address = $('#emailInput');
		if( email_regex.test(email_address.val()) ) {
			email_address.addClass('cleared');
		} else {
			email_address.removeClass('cleared');
		}		
	});
	$('#emailInput').keypress(function(event){
		email_address = $('#emailInput');
		if (event.keyCode == 10 || event.keyCode == 13) {
			event.preventDefault();
			if( email_regex.test(email_address.val()) ) {
				$('#signUp.button').click();
			}
		}
	});
	
	$('#signUp.button').click(function() {
		var post_url = location.protocol + "//" + location.host + "/includes/process.php",
		email_address = $('#emailInput').val();
		test_var = $('#test').val();
		var emailRequest = $.ajax({
			url: post_url,
			type: "POST",
			data: { 
                email: email_address,
                test: test_var    
            }
		});
		emailRequest.done(function(data) {
			console.log(data);
			$('#emailInput').css('font-size','19px').attr({
			  value: data,
			  disabled: 'disabled'
			});
			$('.stay-connected .ninesixty p').text("Thank you for your interest in EMC's news, events and updates.");
			ga('send', 'event', 'form', 'submit', 'Footer Email Subscription');
		});
		return false;
	});
	
	/* ------- SLY -----------------*/
	
	jQuery(function($){
		'use strict';
		(function () {
			var $frame = $('.frame');
			var $slidee = $frame.children('ul').eq(0);
			var $wrap  = $frame.parent();

			// Call Sly on frame
			$frame.sly({
				horizontal: 1,
				itemNav: 'basic',
				smart: 1,
				activateOn: 'click',
				mouseDragging: 1,
				touchDragging: 1,
				releaseSwing: 1,
				startAt: 0,
				scrollBar: $wrap.find('.scrollbar'),
				scrollBy: 1,
				speed: 300,
				elasticBounds: 1,
				easing: 'easeOutExpo',
				dragHandle: 1,
				dynamicHandle: 1,
				clickBar: 1,
			});
		}());
	});

	/* ------- Vimeo FancyBox -----------------*/
	
	$('.fancybox-media').fancybox({
		openEffect  : 'none',
		closeEffect : 'none',
		helpers : {
			media : {}
		}
	});
	
	/* ------- iCulture Slider -----------------*/
	
	$(".royalSlider3").royalSlider({
		imageScalePadding: 0,
		controlNavigation:'none',
		imageScaleMode: 'none',
		imageAlignCenter: true,
		arrowsNav: false,
		numImagesToPreload:2,
		loop: true,
		keyboardNavEnabled: false,
		transitionType: 'fade',
		autoPlay: {
			delay:4000,
			enabled: true,
			pauseOnHover: false
		}
	
	}); 		
	
	$(".royalSlider5").royalSlider({
		imageScalePadding: 0,
		controlNavigation:'bullets',
		arrowsNav: false,
		numImagesToPreload:3,
		loop: true,
		navigateByClick: true,
		sliderDrag: true,
		sliderTouch: true,
		keyboardNavEnabled: true,
		autoPlay: {
			delay:3000,
			enabled: true,
			pauseOnHover: true
		}
	}); 
	
	/* ------- Paradigm Footer Link Functions -----------------*/
    
    $('#sniplyBar').click(function() {
        ga('send', 'event', 'button', 'click', 'PES Modal Opened');
    });
    
    $('#minimizeToggle').click(function(e) {
        $('#sniplyBar').fadeOut();
        ga('send', 'event', 'button', 'click', 'PES Modal Link Window Closed');
        e.stopPropagation();
    });
	
	/* ------- Home Page Vimeo Click Functions -----------------*/
	
	// Script to close modal
	$modal = '<script type="text/javascript">$(\'.vimeo-modal-close\').click(function() { $(\'.vimeo-modal\').fadeOut(1000, function() { $(this).empty(); }) });</script>';
	// Passport video
    $vimeoembed = '<iframe src="//player.vimeo.com/video/161062470?autoplay=1&title=0&byline=0&portrait=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Avenue video
	$vimeoembed2 = '<iframe src="//player.vimeo.com/video/79799928?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Flipgrid video
	$vimeoembed3 = '<iframe src="//player.vimeo.com/video/79717121?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
    $vimeoembed4 = '<iframe src="//player.vimeo.com/video/87866672?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
    $vimeoembed5 = '<iframe src="//player.vimeo.com/video/103519648?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
    $vimeoembed6 = '<iframe src="//player.vimeo.com/video/67900430?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
    // Mirrors & Windows
	$vimeoembed7 = '<iframe src="//player.vimeo.com/video/289361706?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Deustch Aktuell
	$vimeoembed8 = '<iframe src="//player.vimeo.com/video/145441660?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Zhen Bang
	$vimeoembed9 = '<iframe src="//player.vimeo.com/video/145441661?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Symtalk
	$vimeoembed10 = '<iframe src="//player.vimeo.com/video/145681405?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Symtalk Steps 1-3
	$vimeoembed11 = '<iframe src="//player.vimeo.com/video/166842449?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	$vimeoembed12 = '<iframe src="//player.vimeo.com/video/166843240?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	$vimeoembed13 = '<iframe src="//player.vimeo.com/video/166843248?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Italian
	$vimeoembed14 = '<iframe src="//player.vimeo.com/video/242635068?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// A&P
	$vimeoembed15 = '<iframe src="//player.vimeo.com/video/243171073?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Texas ELA
	$vimeoembed16 = '<iframe src="//player.vimeo.com/video/269700411?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Mimundo
	$vimeoembed17 = '<iframe src="//player.vimeo.com/video/260760025?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// ELA Passport
	$vimeoembed18 = '<iframe src="//player.vimeo.com/video/161062470?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	// Zulama
	$vimeoembed19 = '<iframe src="//player.vimeo.com/video/266755499?title=0&amp;byline=0&amp;portrait=0&amp;autoplay=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><div class="vimeo-modal-close"></div>' + $modal;
	
    function bgDim(selector1,selector2,class3) {
        $(selector1).hover(function() {
            $(selector2).addClass(class3);
        }, function() {
            $(selector2).removeClass(class3);
        });
    }	
	function clickVimeo(click,embed) {
		$(click).click(function() {
			$('.vimeo-modal').append(embed).fadeIn();
		});
	}
	function hoverDim(selector1,selector2,selector3) {
		$(selector1).hover(function() {
			$(selector2).css('opacity','1');
			$(selector3).css('opacity','0.3');
		}, function() {
			$(selector2).css('opacity','0');
			$(selector3).css('opacity','1');
		});
	
	}
	
    bgDim('#topImg .header-hero-hover, #topImg .play-button','.header-hero-hover','header-hero-dim');
    bgDim('.fofih-container .play-button','.header-hero-hover-2','header-hero-dim-2');
	clickVimeo('.main #topImg .play-button',$vimeoembed);
    clickVimeo('.quechevere #topImg .play-button',$vimeoembed5);
    clickVimeo('.tes-branche #topImg .play-button',$vimeoembed6);
	clickVimeo('.avenue-play-button .play-button',$vimeoembed2);
	clickVimeo('.iculture #topImg .play-button',$vimeoembed4);
	clickVimeo('.flipgrid-play-button .play-button',$vimeoembed3);
	clickVimeo('.iculture-play-button .play-button',$vimeoembed4);
	clickVimeo('.fofih-container .play-button',$vimeoembed);
	clickVimeo('.mw .play-button',$vimeoembed7);
	clickVimeo('.deutsch-aktuell .play-button',$vimeoembed8);
	clickVimeo('.zhen-bang .play-button',$vimeoembed9);
	//clickVimeo('.symtalk .play-button',$vimeoembed10);
	clickVimeo('.symtalk-play-button-1 .play-button',$vimeoembed11);
	clickVimeo('.symtalk-play-button-2 .play-button',$vimeoembed12);
	clickVimeo('.symtalk-play-button-3 .play-button',$vimeoembed13);
	// Italian
	clickVimeo('.italian .play-button',$vimeoembed14);
	// A&P
	clickVimeo('.ap-hero .play-button',$vimeoembed15);
	// Texas ELA
	clickVimeo('.texas-landing-ela .play-button',$vimeoembed16);
	// Mimundo
	clickVimeo('.mimundo #topImg .play-button',$vimeoembed17);
	// Zulama
    clickVimeo('.al-ca #topImg .play-button',$vimeoembed19);
	
	// M&W Text Links
	 clickVimeo('.mw-landing-text',$vimeoembed7);
	
	hoverDim('.avenue-play-button .play-button','.avenue-play-button-hover-background','.flipgrid-play-button .play-button, .iculture-play-button .play-button');
	hoverDim('.flipgrid-play-button .play-button','.flipgrid-play-button-hover-background','.avenue-play-button .play-button, .iculture-play-button .play-button');
	hoverDim('.iculture-play-button .play-button','.iculture-play-button-hover-background','.avenue-play-button .play-button, .flipgrid-play-button .play-button, .dvd-play-button .play-button');
	hoverDim('.dvd-play-button .play-button','.dvd-play-button-hover-background','.iculture-play-button .play-button');
    
    $(document).on('click','.expandable-box',function() {
        $this = $(this).find('.hidden-content');
        $parent = $this.parent();
        $container = $parent.parent();
        // Add 50px to height because there are a combined 50px of borders added on to the element
        // and since box-sizing: border-box; we need to account for that.
        $height = $this.height() + 50;
        
        $(this).find('.expandable-box-icon').text('-');
        $container.addClass('expandable-box-expanded');
        $parent.css('height',$height);
    });
    
    $(document).on('click','.expandable-box-expanded',function() {
        $(this).find('.expandable-box-icon').text('+');
        $(this).removeClass('expandable-box-expanded');
        $(this).find('.expandable-box-content').css('height','0');
    })    
    
    $(document).on('click','.top-slice .expandable-link', function(e) {
        
        $slideTo = $(this).attr('href');
        $slideTo = $slideTo.replace("#","");
        
        $elem = $('.' + $slideTo);
        $elem.click();
        $pxFromTop = $elem.offset().top - 200;
        
        $('body,html').animate({
	       scrollTop: $pxFromTop
        }, 800);
        
        e.preventDefault();
    });
    
    $('.emc-connect-content').each(function() {
        
        $connectURL = 'https://www.emcp.com/includes/home.php';
        
        $.ajax({
            url: $connectURL,
            method: "POST",
            
        }).done(function(data) {
             $('.emc-connect-posts').html(data);
        });
        
    });
	
	// Slider links
	$('a[href*="#"]')
	// Remove links that don't actually link to anything
	.not('[href="#"]')
	.not('[href="#0"]')
	.click(function(event) {
    // On-page links
    if (
		location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') 
		&& 
		location.hostname == this.hostname
    ) {
		// Figure out element to scroll to
		var target = $(this.hash);
		target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
		// Does a scroll target exist?
		if (target.length) {
			// Only prevent default if animation is actually gonna happen
			event.preventDefault();
			$('html, body').animate({
			scrollTop: target.offset().top-150
        }, 1000, function() {
			// Callback after animation
			// Must change focus!
			var $target = $(target);
			$target.focus();
			if ($target.is(":focus")) { // Checking if the target was focused
				return false;
			} else {
				$target.attr('tabindex','-1'); // Adding tabindex for elements not focusable
				$target.focus(); // Set focus again
			};
        });
      }
    }
	});
});