- name: 'emcp'
  required: true
  box: 'ubuntu/xenial64'
  memory: 512
  cpus: 1
  ip: '172.28.129.28'
  projects:
    emcp: '..'
  mappings:
    '/etc/apache2/sites-enabled': './apache2'
  aliases:
    - 'emcschool.cl.local'
  run_list:
    - 'clw-apache2'
